### PR TITLE
docs: add redirections for new doc structure

### PR DESCRIPTION
**Pull request by aquint-zama**

### CODE REVIEW

**Review by RomanBredehoft — APPROVED** [review]
thanks !

**Comment by RomanBredehoft** [comment]
@aquint-zama feel free to merge the Pr yourself !

**Comment by aquint-zama** [comment]
> The base branch restricts merging to authorized users
It's for you @RomanBredehoft

**Comment by RomanBredehoft** [comment]
ah yes indeed, my bad !

**Comment by aquint-zama** [comment]
Do you backport to the `release/1.5.x` branch?

**Comment by RomanBredehoft** [comment]
not yet no but I'll include it with https://github.com/zama-ai/concrete-ml/pull/608 when updating the branch !

**Pull request merged**
