### PR TITLE
chore: removing these per-model threshold, they are no more needed

### PR DESCRIPTION
**Pull request by bcm-at-zama**
if pytest is green, let's clean that

closes https://github.com/zama-ai/concrete-ml-internal/issues/4088

### CODE REVIEW

**Comment by fd0r** [comment]
Let's just hope we don't create flakies with that

**Comment by bcm-at-zama** [comment]
We can delay this merge, but really, this part of the test is ugly.

**Comment by bcm-at-zama** [comment]
Remark that the only important lines were

```
        "XGBClassifier": 0.7,
        "RandomForestClassifier": 0.8,
```

here

**Comment by RomanBredehoft** [comment]
yes I think it should be fine now ! Note that this test does not consider QNNs because they were flaky / did not make much sense

anyway, you have a conflict btw

**Review by fd0r — APPROVED** [review]

**Comment by bcm-at-zama** [comment]
Rebasing

**Review by fd0r — APPROVED** [review]
If the CI is green that's fine with me!

**Review by RomanBredehoft — APPROVED** [review]
great thanks !

**Pull request merged**
