### PR TITLE
chore: remove manual set of multi and mono strategy

### PR DESCRIPTION
**Pull request by RomanBredehoft**
Recent Concrete- Python integration : 
- fixed the multi strategy problem with linear models
- made multi strategy default in Configuration instances

refs https://github.com/zama-ai/concrete-ml-internal/issues/3889
closes https://github.com/zama-ai/concrete-ml-internal/issues/3862
closes https://github.com/zama-ai/concrete-ml-internal/issues/3860

### CODE REVIEW

**Comment by andrei-stoian-zama** [comment]
Will this not impact @kcelia's PR where she needs to set MONO so CP doesn't crash ?

**Review by fd0r — APPROVED** [review]

**Comment by fd0r** [comment]
I'm guessing this mono/multi issue only affects KNN so she can just set MONO in KNN dedicated test suite no?

**Comment by RomanBredehoft** [comment]
ah yes forgot to mention, this will conflict a bit with @kcelia's PR as I indeed removed `force_mono_parameter_in_configuration` (which she needs to use)

so either I wait for her the merge and then I rebase on main (which I think is best), or I put back the function with `#pragma: no-cover` in it (else pylint will probably complain that it's not used) cc @andrei-stoian-zama @fd0r

**Comment by kcelia** [comment]
Thanks @RomanBredehoft !

**Review by jfrery — COMMENTED** [review]
Nice clean up! I thought KNN was still needing mono params tho?

**Review by andrei-stoian-zama — APPROVED** [review]

**Review by fd0r — APPROVED** [review]

**Pull request merged**
