### PR TITLE
chore: remove old optimization in numpy_gemm

### PR DESCRIPTION
**Pull request by RomanBredehoft**
I believe these optimizations are old, now the compiler should handle them (based on this comment for ex : https://github.com/zama-ai/concrete-compiler-internal/issues/788#issuecomment-1326138981)

do you confirm @bcm-at-zama ? cc @andrei-stoian-zama 

EDIT: actually there was an issue for it in CML (https://github.com/zama-ai/concrete-ml-internal/issues/154) but the one associated to it in old CN (https://github.com/zama-ai/concrete-numpy-internal/issues/1400) has been closes without confirmation that such an optim is done on the compiler side ... maybe @rudy-6-4 @umut-sahin or @BourgerieQuentin can confirm ?

### CODE REVIEW

**Comment by bcm-at-zama** [comment]
I think it's in the compiler but let's be sure: could you ask @BourgerieQuentin about it, by showing him the typical operation we have, and telling him if it's optimized how we expect it to be optimized, please?

**Comment by umut-sahin** [comment]
I believe these are what you're looking for :slightly_smiling_face: 
https://github.com/zama-ai/concrete/blob/cc14e7a4f9d287df3182e690499bfa8d682d2e2b/compilers/concrete-compiler/compiler/lib/Dialect/FHE/IR/FHEOps.cpp#L304-L428

**Comment by fd0r** [comment]
Thanks for the link @umut-sahin !
Looks good then!

**Review by fd0r — APPROVED** [review]

**Comment by RomanBredehoft** [comment]
awesome thanks @umut-sahin !

**Pull request merged**
