### PR TITLE
chore: run ensemble model aggregation in FHE (BLOCKED)

### PR DESCRIPTION
**Pull request by jfrery**
Previously, the summation of tree ensemble's predictions was conducted in clear. 

In this PR, we perform the summation in FHE.

Some experiments have been conducted in this [notebook](https://github.com/zama-ai/fhenets_experiments/blob/main/tree_rounding_experiments/Impact_Sum_Tree.ipynb)

Where study the impact of the FHE summation:
-   Does this approach increase the inference time?
-   Does this approach compromise the model's performance?

Current observations:
- The accuracy is the same, no matter the dataset size.
- RF are slower than xgboost models

closes https://github.com/zama-ai/concrete-ml-internal/issues/451

### CODE REVIEW

**Comment by jfrery** [comment]
If tests pass, I will rerun tree based notebook.

**Comment by jfrery** [comment]
Blocked by https://github.com/zama-ai/concrete-internal/issues/507

**Comment by jfrery** [comment]
Rebasing to check if the bug is still there.

**Comment by andrei-stoian-zama** [comment]
Can we close this one ?

**Pull request closed without merging**
