### PR TITLE
fix: fix a confusing print in docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb

### PR DESCRIPTION
**Pull request by khoaguin**

### CODE REVIEW

**Comment by jfrery** [comment]
Thanks for you contribution @khoaguin. We will merge your PR as soon as the CLA is signed.

**Comment by fd0r** [comment]
After signing the CLA could you also please update your commit message to something like:
> fix: fix a confusing print in docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb

So that it follows our convention (https://www.conventionalcommits.org/en/v1.0.0/), please?

**Comment by khoaguin** [comment]
Done @fd0r. Thanks Luis, this commit convention is useful to know

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by fd0r** [comment]
superseded by https://github.com/zama-ai/concrete-ml/pull/299

**Pull request closed without merging**
