### PR TITLE
chore: remove dependency error setuptools

### PR DESCRIPTION
**Pull request by jfrery**

### CODE REVIEW

**Review by fd0r — DISMISSED** [review]

**Comment by fd0r** [comment]
We need to catch some warning in `make determinism` to make the CI pass

**Comment by RomanBredehoft** [comment]
@fd0r yes the warnings you are refering to are something we've already encountered more than a year ago : https://zama-ai.slack.com/archives/C0455QDGT6C/p1680683773533399?thread_ts=1680683767.733089&cid=C0455QDGT6C

based on what you've said, it seems its directly related to fixing https://github.com/zama-ai/concrete-ml-internal/issues/3407 and https://github.com/zama-ai/concrete-internal/issues/201

**Comment by jfrery** [comment]
Thanks for the commit @fd0r. I am having a look at the problem in this CI.

**Comment by jfrery** [comment]
Closing this as botocore is gone.

**Pull request closed without merging**
