### PR TITLE
Update CONTRIBUTING

### PR DESCRIPTION
**Pull request by sukrucildirr**
file path of contributing.md is fixed.

### CODE REVIEW

**Comment by andrei-stoian-zama** [comment]
Thanks for finding this issue. 

We have systems in place that check for such inconsistencies but this was missed. I thus created a PR which supersedes yours, and it also adds the automatic check. https://github.com/zama-ai/concrete-ml/pull/640 

I'm closing this one and going forward with the other one. 

Thanks again!

**Comment by aquint-zama** [comment]
@cla-bot check
(just to check CLA is properly verified)

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by aquint-zama** [comment]
Ready for next contribution @sukrucildirr 😉

**Comment by sukrucildirr** [comment]
Thanks 🫡

**Pull request closed without merging**
