### PR TITLE
chore: update poetry to 1.7.1

### PR DESCRIPTION
**Pull request by fd0r**

### CODE REVIEW

**Comment by bcm-at-zama** [comment]
Hopefully it will help!

**Review by RomanBredehoft — CHANGES_REQUESTED** [review]
it's not the only place you need to update it, there is also : 
- `.github/workflows/prepare_release.yaml`
- `.github/workflows/update_licenses.yaml`
- `script/make_utils/setup_os_deps.sh`

you can look for `1.2.2` in the project

**Review by jfrery — CHANGES_REQUESTED** [review]
What about the other places where we have this 1.2.2? We should probably update them.

```
5 results - 4 files

src • Makefile:
  14  PYTEST_OPTIONS:=
  15: POETRY_VERSION:=1.2.2
  16  APIDOCS_OUTPUT?="./docs/developer-guide/api"

src • .github/workflows/prepare_release.yaml:
  61            python -m pip install --upgrade pip
  62:           python -m pip install poetry==1.2.2
  63            make setup_env

src • .github/workflows/update_licenses.yaml:
  48            python -m pip install --upgrade pip
  49:           python -m pip install poetry==1.2.2
  50            make setup_env

src • script/make_utils/setup_os_deps.sh:
  140          python3 -m pip install --no-cache-dir --upgrade pip && \
  141:         python3 -m pip install --no-cache-dir --ignore-installed poetry==1.2.2 && \
  142          linux_install_gitleaks && linux_install_actionlint && linux_install_github_cli"

  153      python3 -m pip install -U pip
  154:     python3 -m pip install poetry==1.2.2
  155  
```

**Comment by fd0r** [comment]
Oups yeah nice catch thanks, will update everywhere

**Comment by fd0r** [comment]
Alright it looks like this is blocked by `skorch` weird `\s` character.

Closing this for now.
I don't see any issue with using higher versions on our systems though

**Comment by RomanBredehoft** [comment]
>  I don't see any issue with using higher versions on our systems though

if we don't have the same versions between our CI and our systems, we probably will start to encounter divergences in our lock files or similar stuff (which is why we've done : https://github.com/zama-ai/concrete-ml-internal/issues/2740)

**Pull request closed without merging**
