### PR TITLE
docs: add example notebook for linearSVR

### PR DESCRIPTION
**Pull request by oboulant**
This notebook introduces an example on how to use linearSVR and a comparison with sklearn.

It is inspired by :

https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/LinearRegression.ipynb
https://github.com/zama-ai/concrete-ml/blob/release/0.6.x/docs/advanced_examples/XGBClassifier.ipynb
https://github.com/zama-ai/concrete-ml/blob/release/0.6.x/docs/advanced_examples/DecisionTreeClassifier.ipynb

It has been validated here : https://github.com/zama-ai/fhe-tutorials/pull/4

### CODE REVIEW

**Comment by aquint-zama** [comment]
submission for bounty application: https://github.com/zama-ai/bounty-program/issues/12

**Comment by jfrery** [comment]
Hello @oboulant and thanks again for your work! We would like to proceed to the merge. Could you rebase on the https://github.com/zama-ai/concrete-ml/tree/tutorials branch please?

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by oboulant** [comment]
> Hello @oboulant and thanks again for your work! We would like to proceed to the merge. Could you rebase on the https://github.com/zama-ai/concrete-ml/tree/tutorials branch please?

Hi @jfrery , when trying to rebase / merge on the upstream `tutorials` branch, it tells me everything is Already up to date.

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by oboulant** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Roman**. This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

I checked, everything is fine on my end !

**Comment by aquint-zama** [comment]
> I checked, everything is fine on my end !

It's on our side don't worry, but I think that if you rebase on zama-ai:tutorials and keep only your commit with the tutorial it should work (there is 20 commits in the PR currently)

**Comment by jfrery** [comment]
Hello @oboulant if that's fine with you we would like to merge your PR. We are waiting for the cla to be signed on your end.

**Comment by oboulant** [comment]
> Hello @oboulant if that's fine with you we would like to merge your PR. We are waiting for the cla to be signed on your end.

Hi @jfrery , 
cla ?

**Comment by aquint-zama** [comment]
To fix the cla issue you need to rebase on an updated zama-ai:tutorials branch (this PR should be only 1 commit)

**Comment by oboulant** [comment]
@aquint-zama @jfrery 
I am having troubles rebasing with the upstream `zama-ai:tutorials` branch. For some reason it tells me my local branch is up to date whenever I try to rebase or merge on `zama-ai:tutorials`. 

Is that okay if I just open a new PR and I will started my local branch from the upstream `zama-ai:tutorials` ? I guess it should solve the issue.

**Comment by jfrery** [comment]
Hello @oboulant no worry. We will handle this internally. Your commit will be merged with our internal branch and published at the next release. Thanks again for your work!

**Comment by oboulant** [comment]
> Hello @oboulant no worry. We will handle this internally. Your commit will be merged with our internal branch and published at the next release. Thanks again for your work!

Very nice, thank you ! 

Sorry for the last inconvenience with the rebase, I really tried everything to the best of my knowledge. I should not have started my PR from `release/1.0.x` but rather should have created my own branch... I guess I was distracted...

**Pull request merged**
