### PR TITLE
Add developer survey in doc

### PR DESCRIPTION
**Pull request by yuxizama**
Added the developer survey banner in the most viewed docs and README page to promote the survey and gather feedback.

### CODE REVIEW

**Review by RomanBredehoft — DISMISSED** [review]
thanks !

**Review by RomanBredehoft — DISMISSED** [review]

**Comment by yuxizama** [comment]
Hey @RomanBredehoft 
I made a small adjustment yesterday and it seems like some tests have failed.
For this message below I don't really understand what happened. 😅

>  "@[yuxizama](https://github.com/yuxizama) yuxizama dismissed [RomanBredehoft](https://github.com/RomanBredehoft)’s [stale review](https://github.com/zama-ai/concrete-ml/pull/830#pullrequestreview-2219004074) via [c7a6f22](https://github.com/zama-ai/concrete-ml/commit/c7a6f22eb5e37a63386b691a350dd580ab4ef84b) [18 hours ago](https://github.com/zama-ai/concrete-ml/pull/830#event-13779871676)"

Could you please help to check? 
Besides, I would like to merge the same changes into the 1.6 branch so that i can be reflected on the Documentation website, but I'm not sure what's the best way to do it. Should I create another PR with these changes for 1.6 branch?
Thank you!

**Comment by RomanBredehoft** [comment]
Yes @yuxizama , sorry for the delay, I just committed and it should fix the issue ! 

And no worries for Gitub's message, in this repo we've enabled a setting which makes new commits dismiss all approval from PRs (we prefer to re-review if new changes have been made) 😉 

as for 1.6 yes the idea is to open a new PR targeting the `release/1.6.x` branch and include the same changes !

**Comment by yuxizama** [comment]
Great @RomanBredehoft thank you so much! I'll do it for the 1.6 branch

**Review by RomanBredehoft — APPROVED** [review]

**Review by andrei-stoian-zama — APPROVED** [review]

**Review by kcelia — APPROVED** [review]

**Pull request merged**
