### PR TITLE
fix: minor doc change

### PR DESCRIPTION
**Pull request by bcm-at-zama**
Minor doc change requested by @yuxizama 

Can you @zama-ai/machine-learning also have it applied in the 1.5 branch please

### CODE REVIEW

**Comment by RomanBredehoft** [comment]
is it the only thing to change I was that Yuxi asked for several changes on slack, so better to do everything at once imo 

also, you just need to open another PR targeting the 1.5.x branch to update it, nothing more

**Comment by bcm-at-zama** [comment]
if you want to apply her change in @andrei-stoian-zama 's branch, fine with me, ML team can close my PR

**Comment by RomanBredehoft** [comment]
yes it would make sense to me to do everything at the same time

**Comment by RomanBredehoft** [comment]
@bcm-at-zama  let's merge this in main actually as we are including it in the release branch with https://github.com/zama-ai/concrete-ml/pull/603, but you need to fix conformance first

**Review by jfrery — APPROVED** [review]

**Pull request merged**
