### PR TITLE
chore: avoid utils.py files in use case examples

### PR DESCRIPTION
**Pull request by RomanBredehoft**
This should fix import errors some users faced 

closes https://github.com/zama-ai/concrete-ml-internal/issues/3854
refs https://github.com/zama-ai/concrete-ml/issues/96

### CODE REVIEW

**Review by andrei-stoian-zama — COMMENTED** [review]
Can we have a make pcc thing that prevents utils.py files on our source tree ? 

It can be done in a second PR if you want

**Comment by RomanBredehoft** [comment]
> fine with me even if not sure what's the point

@fd0r we've recently had users that encountered issues with the utils.py files not being recognized as a local file even in a virtual env (for example: https://github.com/zama-ai/concrete-ml/issues/96)

**Comment by fd0r** [comment]
hummmm do we have an explanation for this?
looks weird to me

**Review by andrei-stoian-zama — APPROVED** [review]
Great!

**Pull request merged**
