### PR TITLE
Update protobuf version

### PR DESCRIPTION
**Pull request by mohammadnaseri**
This PR updates protobuf dependency.

### CODE REVIEW

**Comment by aquint-zama** [comment]
Hello @mohammadnaseri and thanks for your contribution, is it possible for you to sign again the CLA making sure you fill the entire appropriate section, fields are made optionals as you could sign for an individual or for a company but you should fill all fields 😉

**Comment by mohammadnaseri** [comment]
> Hello @mohammadnaseri and thanks for your contribution, is it possible for you to sign again the CLA making sure you fill the entire appropriate section, fields are made optionals as you could sign for an individual or for a company but you should fill all fields 😉

Hi, I just singed a new form and filled those fields as well.

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by jfrery** [comment]
This has been merged in https://github.com/zama-ai/concrete-ml/pull/878.

**Pull request closed without merging**
