### PR TITLE
chore: fix sync repository action (bis)

### PR DESCRIPTION
**Pull request by RomanBredehoft**
it's still failing : https://github.com/zama-ai/concrete-ml/actions/runs/8522402034/job/23342541783

the issue is that the external action does not provide any LFS options

also, it looks like we were cloning the repo twice, so I remove the external action and simplified to these steps

### CODE REVIEW

**Comment by RomanBredehoft** [comment]
I'm usually not a fan of doing this when we are doing things related to main, but in this case I think it should be good indeed, will do thanks !

**Comment by RomanBredehoft** [comment]
I can't find a way to make this work, it's pretty weird

**Review by jfrery — APPROVED** [review]
Thanks for fixing this!

**Comment by RomanBredehoft** [comment]
finally working 🎉

**Review by jfrery — APPROVED** [review]

**Pull request merged**
