### PR TITLE
chore: custom cp for cifar bench

### PR DESCRIPTION
**Pull request by rudy-6-4**
This helps to launch the bench using an alternative wheel from concrete CI and alternative concrete python branch

### CODE REVIEW

**Comment by fd0r** [comment]
Nice to have but I would verify that we log some hash of Concrete Python to be able to identify which version of CP was used.

IIRC we currently log the git hash of the repo but this change means that the version used won't be the one in `poetry.lock` thus not tracked in the git hash.

**Comment by RomanBredehoft** [comment]
also could you rename your commit by "feat: custom cp for cifar branch" ? since you've opened your PR we've removed the scopes in commit messages and I worry that it will make the CI fail when merging into main ! thanks

**Comment by fd0r** [comment]
Actually @RomanBredehoft this is more a `chore` than `feat` imo since this doesn't add anything to the end-user.

**Review by fd0r — CHANGES_REQUESTED** [review]
Two comments/questions:
- IMO this isn't a `feat` but a `chore`
- What would be the result of `    from importlib.metadata import version; version("concrete-python")` ?

**Comment by RomanBredehoft** [comment]
yes you're right @fd0r I did not realize that

**Comment by rudy-6-4** [comment]
> Two comments/questions:
> 
>     * IMO this isn't a `feat` but a `chore`
> 
>     * What would be the result of `from importlib.metadata import version; version("concrete-python")` with a custom build? We use it to track the improvements in the benchmark database so I'm afraid it will mess things up.
>       
>       * If we have some hash that identifies the version using `version("concrete-python")` then that's fine with me
>       * Otherwise we should find a way to detect it or just skip the upload to the DB step if we are using a custom version of Concrete

I disabled the upload for such cases as it could be arbitrary wip branch & wheel that are not easy to identify.

**Review by fd0r — APPROVED** [review]

**Review by RomanBredehoft — APPROVED** [review]

**Pull request merged**
