### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by yuxizama**

### CODE REVIEW

**Review by RomanBredehoft — CHANGES_REQUESTED** [review]
there are other similar changes to be done, I'll push them here as well, but thanks for these yes !

**Comment by bcm-at-zama** [comment]
@RomanBredehoft : how did you find those additional changes?

**Comment by RomanBredehoft** [comment]
just with ctrl + f , I asically just removed all `https` links, but we might still have some broken links as I didn't / couldn't check all relative references , hence why I opened this issue : https://github.com/zama-ai/concrete-ml-internal/issues/4372

**Review by RomanBredehoft — APPROVED** [review]
now good !

**Pull request merged**
